FROM ubuntu:22.04

ENV GLIBC_VERSION 2.35-r0

RUN useradd -s /bin/bash -m vscode \
  && groupadd docker \
  && usermod -aG docker vscode

RUN apt update -y \ 
&& apt install -y build-essential \
cmake \
clang \
gdb \
git \
pkg-config \
wget

RUN wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1_amd64.deb \
&& dpkg -i libssl1.1_1.1.1l-1ubuntu1_amd64.deb

USER vscode
