name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  TEST_DIR: wintercpp_test
  CACHE_DIR: ~/winter

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: ninja
      run: sudo apt-get install -y ninja-build
      
    - name: configure
      uses: actions/cache@v2
      id: cache-winter
      with:
        path: "~/winter"
        key: winter-${{ hashFiles('wintercpp/dependencies.cmake') }}
        restore-keys: winter-
    - name: Configure and build winter
      env:
        CACHE_HIT: ${{steps.cache-winter.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          sudo cp --force --recursive ~/winter/build/* ${{github.workspace}}/build/
          #sudo cp --force --recursive ~/winter/cache/* ${{github.workspace}}/.cache/
          sudo cp --force --recursive ~/winter/wintercpp/third_party/* ${{github.workspace}}/wintercpp/third_party/
          sudo cp --force --recursive ~/winter/wintercpp_test/third_party/* ${{github.workspace}}/wintercpp_test/third_party/
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        else
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
          #cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          mkdir -p ~/winter
          #mkdir -p ~/winter/cache
          mkdir -p ~/winter/build
          mkdir -p ~/winter/wintercpp/third_party
          mkdir -p ~/winter/wintercpp_test/third_party
          sudo cp --force --recursive ${{github.workspace}}/build/* ~/winter/build/
          #sudo cp --force --recursive ${{github.workspace}}/.cache/* ~/winter/cache/
          sudo cp --force --recursive ${{github.workspace}}/wintercpp/third_party/* ~/winter/wintercpp/third_party/
          sudo cp --force --recursive ${{github.workspace}}/wintercpp_test/third_party/* ~/winter/wintercpp_test/third_party/
        fi
        
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} 
      
    - name: Test
      working-directory: ${{github.workspace}}/build/${{env.TEST_DIR}}
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
