name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  TEST_DIR: wintercpp_test

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # install dependencies
    - name: ninja
      run: sudo apt-get install -y ninja-build
      
    - name: Cache cmake
      uses: actions/cache@v2.1.6
      id: cache-cmake
      with:
        path: "~/winter"
        key: cmake-build
    - name: Configure and build winter
      env:
        CACHE_HIT: ${{steps.cache-cmake.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          sudo cp --force --recursive ~/winter/build/* ${{github.workspace}}/build/
          sudo cp --force --recursive ~/winter/.cache/* ${{github.workspace}}/build/.cache/
          sudo cp --force --recursive ~/winter/wintercpp/third_party/* ${{github.workspace}}/wintercpp/third_party/
          sudo cp --force --recursive ~/winter/wintercpp_test/third_party/* ${{github.workspace}}/wintercpp_test/third_party/
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        else
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          mkdir -p ~/winter
          sudo cp --force --recursive ${{github.workspace}}/build/* ~/winter/build/
          sudo cp --force --recursive ${{github.workspace}}/build/.cache/* ~/winter/.cache/
          sudo cp --force --recursive ${{github.workspace}}/wintercpp/third_party/* ~/winter/wintercpp/third_party/
          sudo cp --force --recursive ${{github.workspace}}/wintercpp_test/third_party/* ~/winter/wintercpp_test/third_party/
        fi

    - name: Test
      working-directory: ${{github.workspace}}/build/${{env.TEST_DIR}}
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
